apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shivamsharma20work-afk/retail-shop-gitOps.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true