apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - secrets.yml
  - jenkins-sa.yml
  - jenkins-rolebinding.yml

  - backend-k8s/deployment.yml
  - backend-k8s/service.yml
  - frontend-k8s/deployment.yml
  - frontend-k8s/service.yml

  - configMap.yml
  - ingress.yml
  - hpa.yml
